---
title: "Assessing the Anthropogenic Impact on West Indian Coral Reefs"
subtitle: "Halftime Seminar"
author: Hadrien Gourlé
date: September 27, 2018
output:
    revealjs::revealjs_presentation:
        theme: sky
        highlight: pygments
        center: true
        slideNumber: true
        transition: slide
        template: assets/templates/template.html
        css: assets/css/custom.css
        reveal_options:
            slideNumber: true
---
 
# {#intro-slide data-background="assets/img/background.jpg"}

## {#intro-slide data-background="assets/img/background.jpg"}

<div id="intro-text-box">Coral reefs are one of the most diverse ecosystem on the planet.</div><br>
<div id="intro-text-box" class="fragment fade-left">They face great challenges and their population is rapidely declining.</div><br>
<div id="intro-text-box" class="fragment fade-left">Can research help?</div>

## Where?

```{r map, echo=FALSE, dev.args = list(bg = 'transparent')}
library(ggplot2)
library(ggmap)
library(maps)
library(mapdata)
africa <- map_data("world")

mau <- data.frame(
  long = c(57.5522),
  lat = c(-20.3484))
kenya <- map_data("world", region = "Kenya")
# mauritius <- map_data("world", region = "Mauritius")
ggplot() +
    geom_polygon(data = africa, color = "white",
                 aes(x=long, y = lat, group = group)) +
    geom_polygon(data = kenya, fill = "red",
                 aes(x=long, y = lat, group = group)) +
    # geom_polygon(data = mauritius, fill = "red",
                 # aes(x=long, y = lat, group = group, size = 40)) +
    geom_point(data = mau, aes(x = long, y = lat), color = "red", size = 2) +
    coord_fixed(1.3) +
    xlim(-18, 58) + ylim(-35, 40) +
    xlab("") +
    ylab("") +
    theme_minimal() +
    theme(axis.text.x = element_blank(), axis.text.y = element_blank(),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank())
```

## What?

- Monitor the health of coral reefs using bacterial communities
- Characterize the relationship between corals and their microbial environment

# Survey of the field

## Literature review

- previous studies focusing on 16S
- limited power, no functional insight?

## Are there global patterns?

- analysis in progress

# Whole metagenome Sequencing

- Function / metabolism
- is hard to analyse

## Taxonomy classification

- blast
- diamond
- kraken
- kaiju
- centrifuge
- despi
- sourmash
- salmon
- mmseqs2
- rapsearch
- ...

## Let's benchmark!

> Gourlé, Hadrien, et al. "Simulating Illumina Metagenomic Data with InSilicoSeq." Bioinformatics (2018).

```
pip install insilicoseq
iss generate -h
```

## Results of benchmarking hopefully coming at the end of this year

# Applying WMS to coral reef communities

## Surrounding the reef

*TODO*

## A dive in the coral reef microbiome

*TODO*
